### ISSUE TITLE
Crashes on activation

### ISSUE THREAD

**Issue by BarryCarlyon** [jason0611/FS19_HeadlandManagement#24]
Under v1.1.1.0 released on modhub today.

When I activate Headland management.

The camera "disconnects" from the tractor.
Guidance Steering stays enabled.
Cruise Control speed stays on the same speed.
Tools don't lift/turn off
I can't switch vehicles

If I hit escape to go into the menu.
I'm now _stuck_ in the menu

And my "toggle headland managmenet" button doesn't turn it off again.

Some jiggery pokery here and their I managed to completely trash the dashboard (speedo is totally murdered)

Somethings super screwy somewhere.

**Comment by jason0611** [comment]
Can you please send me the game's logfile? It's working fine here...

**Comment by BarryCarlyon** [comment]
It's "spamming"

```
2021-11-02 18:39 Error: Running LUA method 'update'.
2021-11-02 18:39 H:/barry/Documents/My Games/FarmingSimulator2019/mods/FS19_HeadlandManagement/headlandManagement.lua:567: attempt to index local 'actVehicle' (a nil value)
```

I activate headline management at the one minute mark.
Cruise control is on
machine is on
guidance steering is on.

One Log File

[log.txt](https://github.com/jason0611/FS19_HeadlandManagement/files/7463275/log.txt)

One Video File

https://user-images.githubusercontent.com/20999/139925487-d007bb5c-9afe-44df-8720-9d5e184dc4d7.mp4

**Comment by BarryCarlyon** [comment]
I wonder if it's something related to me using this mod

https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=129888

Which modifies the attachement/connector rules/logic? (Clutching at straws)

**Comment by jason0611** [comment]
No, I'm using ManualAttach, too. 
I guess it's TowBar, because this Mod makes real strange things with the Attachers. When I'm at home in half an hour, I will look further into it.

**Comment by BarryCarlyon** [comment]
Yup Confirmed.

Disabled that mod and gave it another go and no more explosions!

**Comment by jason0611** [comment]
Ok. This is a conflict I can't mitigate because of the style towBar is programmed. I only can restrict my mod to the first attacher joint if towBar or towBarWeight is active. 
For towing purposes I recommend FS19_TowingChain, that works fine here.

**Comment by BarryCarlyon** [comment]
I'll talk a look at towing chain.

You might just need/want to add a check for nil so it deson't explode peoples games?

**Comment by jason0611** [comment]
Of course I will do this, but this will restrict HeadlandManagement to just one attacher joint if towBar or towingWeight is present.

**Comment by jason0611** [comment]
Would you like to try it out?
[FS19_HeadlandManagement.zip](https://github.com/jason0611/FS19_HeadlandManagement/files/7463760/FS19_HeadlandManagement.zip)

**Comment by jason0611** [comment]
Hotfix is uploaded to ModHub and will be available soon. :-)
Thank you for your support.

**Comment by jason0611** [comment]
Hotfix is available at ModHub now, so I will close this issue.
